import org.junit.jupiter.api.Test

import org.junit.jupiter.api.Assertions.*

class Day11Test {
    val solver = Day11()

    @Test
    fun solvePart1() {
        val input = """
            ...#......
            .......#..
            #.........
            ..........
            ......#...
            .#........
            .........#
            ..........
            .......#..
            #...#.....
        """.trimIndent().lines()
        assertEquals("374", solver.solvePart1(input))
    }

    @Test
    fun solvePart2_2() {
        val input = """
            ...#......
            .......#..
            #.........
            ..........
            ......#...
            .#........
            .........#
            ..........
            .......#..
            #...#.....
        """.trimIndent().lines()
        assertEquals("374", solver.solveWithFactor(2, input))
    }

    @Test
    fun solvePart2_10() {
        val input = """
            ...#......
            .......#..
            #.........
            ..........
            ......#...
            .#........
            .........#
            ..........
            .......#..
            #...#.....
        """.trimIndent().lines()
        assertEquals("1030", solver.solveWithFactor(10, input))
    }

    @Test
    fun solvePart2_100() {
        val input = """
            ...#......
            .......#..
            #.........
            ..........
            ......#...
            .#........
            .........#
            ..........
            .......#..
            #...#.....
        """.trimIndent().lines()
        assertEquals("8410", solver.solveWithFactor(100, input))
    }
}